<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XCascader extends XTemplate
{
    public $is_dynamic = false;

    public $content;
    public $contentS;
    public $params;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($title, $val, $name, $note, $data, $option = [])
    {
        parent::__construct();
        $this->params = [
            'title' => $title,
            'val' => $val,
            'name' => $name,
            'note' => $note,
            'data' => $data,
        ];
        $this->params = array_merge($this->params, ParseParams::getParams($option));
    }

    function getModel()
    {
        //判断是否是表单内
        if (isset($this->params['form_name'])) {
            $list = explode('.', $this->params['form_name']);
            $data[$list[0]][$list[1]] = $this->params['val'];
        } else {
            $data[$this->params['name']] = $this->params['val'];
        }
        $data[$this->params['name'] . "_options"] = $this->params['data'];
        return $data;
    }

    function getRules()
    {
        return $this->rules;
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentS = $this->fetch('element/form_cascader.php', $this->params);
        } else {
            $this->contentS = $this->fetch('include/form_input.php', $this->params);
        }

        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show(Dom $root)
    {
        parent::show($root);
    }
}
