<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XDivider extends XTemplate
{
    public $is_dynamic = false;

    public $content;
    public $contentS;
    public $params;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($content = "", $position = 1, $icon = "")
    {
        switch ($position) {
            case 1:
                $position = "left";
                break;
            case 2:
                $position = "center";
                break;
            case 3:
                $position = "right";
                break;
            default:
                $position = "center";
        }
        if ($icon) {
            $icon = "<i class='" . $icon . "'></i>";
        }
        parent::__construct();
        $this->params = [
            "content" => $content,
            "position" => $position,
            "icon" => $icon,
        ];
    }

    function getRules()
    {
        return $this->rules;
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentS = $this->fetch('element/divider.php', $this->params);
        } else {
            $this->contentS = "";
        }

        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show(Dom $root)
    {
        parent::show($root);
    }
}
