<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XForm extends XTemplate
{
    public $is_dynamic = false;

    public $content;

    public $contentS;
    public $contentE;

    /**
     * @var Dom
     */
    public $decorate;

    function __construct($title, $form_name, $method, $url)
    {
        parent::__construct();
        $this->contentS = $this->fetch('include/form_start.php', [
            'method' => $method,
            'action' => $url,
            'title' => $title,
            'form_name' => $form_name,
        ]);
        $this->contentE = $this->fetch('include/form_end.php', []);
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
        echo $this->contentE;
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show()
    {
        parent::show();
    }
}