<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XForm extends XTemplate
{
    public $is_dynamic = false;

    public $content;

    public $contentS;
    public $contentE;
    public $params;
    public $isForm;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($title, $form_name, $method, $url, $rules = [])
    {
        parent::__construct();
        $this->isForm = true;
        $this->rules = $rules;
        $this->params = [
            'title' => $title,
            'form_name' => $form_name,
            'method' => $method,
            'url' => $url,
            'rules' => $rules
        ];
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentS = $this->fetch('element/form_start.php', $this->params);
        } else {
            $this->contentS = $this->fetch('include/form_start.php', $this->params);
        }
        echo $this->contentS;
    }

    function methodSubmit()
    {
        return '
         submitForm(formName) {
                this.$refs[formName].validate((valid) => {
                    if (valid) {
                        alert("submit!");
                    } else {
                        console.log("error submit!!");
                        return false;
                    }
                });
            }
        ';
    }

    function methodResetForm()
    {
        return '
          resetForm(formName) {
                this.$refs[formName].resetFields();
            }
        ';
    }

    function getMethods()
    {
        $this->methods[] = $this->methodSubmit();
        $this->methods[] = $this->methodResetForm();
        return $this->methods;
    }

    function getRules()
    {
        return $this->rules;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentE = $this->fetch('element/form_end.php', $this->params);
        } else {
            $this->contentE = $this->fetch('include/form_end.php', $this->params);
        }
        echo $this->contentE;
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function setDecorate($decorate)
    {
        parent::setDecorate($decorate); // TODO: Change the autogenerated stub
        //将表单的名字注入插件
        $decorate->params['form_name'] = $this->params['form_name'] . "." . $decorate->params['name'];
    }

    function show(Dom $root)
    {
        parent::show($root);
    }
}