<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XForm extends XTemplate
{
    public $is_dynamic = false;

    public $content;

    public $contentS;
    public $contentE;
    public $params;
    public $isForm;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($title, $form_name, $method, $url, $rules = [])
    {
        parent::__construct();
        $this->isForm = true;
        $this->params = [
            'title' => $title,
            'form_name' => $form_name,
            'method' => $method,
            'url' => $url,
            'rules' => $rules
        ];
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentS = $this->fetch('element/form_start.php', [
                'method' => $this->params['method'],
                'action' => $this->params['url'],
                'title' => $this->params['title'],
                'form_name' => $this->params['form_name'],
            ]);
        } else {
            $this->contentS = $this->fetch('include/form_start.php', [
                'method' => $this->params['method'],
                'action' => $this->params['url'],
                'title' => $this->params['title'],
                'form_name' => $this->params['form_name'],
            ]);
        }
        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentE = $this->fetch('element/form_end.php', []);
        } else {
            $this->contentE = $this->fetch('include/form_end.php', []);
        }
        echo $this->contentE;
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function setDecorate($decorate)
    {
        parent::setDecorate($decorate); // TODO: Change the autogenerated stub
        //将表单的名字注入插件
        $decorate->params['name'] = $this->params['form_name'] . "." . $decorate->params['name'];
    }

    function show(Dom $root)
    {
        parent::show($root);
    }
}