<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XLeftMenu extends XTemplate
{
    public $is_dynamic = false;

    public $contentS;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($controller, $view, $menuList)
    {
        parent::__construct();
        $menu = new Menu($controller, $view);
        foreach ($menuList as $mainList) {
            $menu->main($mainList['icon'], $mainList['name'], $mainList['url']);
            foreach ($mainList['sub_menus'] as $sub_menu) {
                $menu->sub($sub_menu['icon'], $sub_menu['name'], $sub_menu['url'], $sub_menu['controller'], $sub_menu['view']);
            }
        }
        $content = "<aside id=\"left-panel\">";
        $content .= $menu->create();
        $content .= "<span class=\"minifyme\"> <i class=\"fa fa-arrow-circle-left hit\"></i> </span></aside>";
        $this->contentS = $content;
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show()
    {
        parent::show();
    }
}