<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XMainFooter extends XTemplate
{
    public $is_dynamic = false;

    public $content;


    /**
     * @var Dom
     */
    public $decorate;

    function __construct()
    {
        parent::__construct();
        $content = $this->fetch('include/main_footer.php', []);
        $this->content = $content;
    }
    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        echo $this->content;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show()
    {
        parent::show();
    }
}