<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XMainContent extends XTemplate
{
    public $is_dynamic = false;

    public $content;

    public $contentS;
    public $contentE;
    public $params;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct($title)
    {
        parent::__construct();
        $this->params = [
            'title' => $title
        ];

    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        if ($this->isElement) {
            $this->contentS = $this->fetch('element/main_start.php', [
                'title' => $this->params['title']
            ]);
        } else {
            $this->contentS = $this->fetch('include/main_start.php', [
                'title' => $this->params['title']
            ]);
        }

        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
        if($this->isElement){
            $this->contentE = $this->fetch('element/main_end.php', []);
        }else{
            $this->contentE = $this->fetch('include/main_end.php', []);
        }
        echo $this->contentE;
    }

    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show(Dom $root)
    {
        parent::show($root);
    }
}