<?php
/**
 * Created by PhpStorm.
 * User: xiangdongdong
 * Date: 2019/5/24
 * Time: 18:21
 */

namespace Component;

use Interfaces\Dom;

class XMainHeader extends XTemplate
{
    public $is_dynamic = false;

    public $content;

    public $contentS;
    /**
     * @var Dom
     */
    public $decorate;

    function __construct()
    {
        parent::__construct();
        $content = $this->fetch('include/main_header.php', []);
        if ($this->is_dynamic) {
            $this->content .= $content;
        }
        $this->contentS = $content;
    }

    function contentS()
    {
        parent::contentS(); // TODO: Change the autogenerated stub
        echo $this->contentS;
    }

    function contentE()
    {
        parent::contentE(); // TODO: Change the autogenerated stub
    }
    function decorate(Dom $dom)
    {
        $this->decorate = $dom;
        return $dom;
    }

    function show()
    {
        parent::show();
    }
}